//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProblemManagementWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACO_params
    {
        public long problemId { get; set; }
        public int populationSize { get; set; }
        public float beta { get; set; }
        public int gamma { get; set; }
        public float ro { get; set; }
        public int maxIterations { get; set; }
    
        public virtual Problem Problem { get; set; }
    }
}
