//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProblemManagementWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CspContext : DbContext
    {
        public CspContext()
            : base("name=CspContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACO_params> ACO_params { get; set; }
        public virtual DbSet<GA_params> GA_params { get; set; }
        public virtual DbSet<PatternOrder> PatternOrders { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<ProblemOrder> ProblemOrders { get; set; }
        public virtual DbSet<ProblemStatu> ProblemStatus { get; set; }
        public virtual DbSet<SolutionPattern> SolutionPatterns { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<StockType> StockTypes { get; set; }
    }
}
