//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProblemManagementWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatternOrder
    {
        public long patternId { get; set; }
        public int orderId { get; set; }
        public int quantity { get; set; }
        public int cachedLength { get; set; }
    
        public virtual SolutionPattern SolutionPattern { get; set; }
    }
}
