//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProblemManagementWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Problem()
        {
            this.ProblemOrders = new HashSet<ProblemOrder>();
        }
    
        public long problemId { get; set; }
        public int status { get; set; }
        public int material { get; set; }
        public int algorithm { get; set; }
        public System.DateTime dateAssinged { get; set; }
        public System.DateTime dateSolved { get; set; }
        public string note { get; set; }
        public int cutWidth { get; set; }
    
        public virtual ACO_params ACO_params { get; set; }
        public virtual GA_params GA_params { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProblemOrder> ProblemOrders { get; set; }
    }
}
