//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProblemManagementWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolutionPattern
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolutionPattern()
        {
            this.PatternOrders = new HashSet<PatternOrder>();
        }
    
        public long problemId { get; set; }
        public int solutionId { get; set; }
        public long patternId { get; set; }
        public int quantity { get; set; }
        public int stock { get; set; }
        public int trimLength { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatternOrder> PatternOrders { get; set; }
    }
}
