//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProblemManagementWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int materialType { get; set; }
        public int materialLength { get; set; }
        public int quantity { get; set; }
        public int stockId { get; set; }
    
        public virtual StockType StockType { get; set; }
    }
}
